FROM eclipse-temurin:17.0.6_10-jre

ENV SPRING_JPA_GENERATE_DDL=true
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV SPRING_APPLICATION_NAME=lab4-characters
ENV PROFESSION_URL=http://spring-characters:8080
ENV SERVER_PORT=8080

ENV SPRING_DATASOURCE_URL=jdbc:h2:mem:simple-rpg
ENV SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
ENV SPRING_DATASOURCE_USERNAME=admin
ENV SPRING_DATASOURCE_PASSWORD=password
ENV SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect

EXPOSE 8080

COPY lab4-characters/target/lab4-characters-1.0-SNAPSHOT.jar /opt/lab-6-characters/lab6-prof.jar

CMD ["java", "-jar", "/opt/lab-6-characters/lab6-prof.jar"]

# docker build -t d4m14n/aui-6-characters:v1.0 .\characters
# docker run --rm -p 8080:8080  -dit d4m14n/aui-6-characters:v1.0