FROM eclipse-temurin:17.0.6_10-jre

ENV SPRING_JPA_GENERATE_DDL=true
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV SPRING_APPLICATION_NAME=lab4-characters
ENV PROFESSION_URL=http://spring-characters:8080
ENV SERVER_PORT=8080

ENV SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/characters_db"
ENV SPRING_DATASOURCE_DRIVERCLASSNAME="org.postgresql.Driver"
ENV SPRING_DATASOURCE_USERNAME="characters_user"
ENV SPRING_DATASOURCE_PASSWORD="characters_password"
ENV SPRING_JPA_DATABASE_PLATFORM="org.hibernate.dialect.PostgreSQLDialect"

EXPOSE 8080

COPY lab4-characters/target/lab4-characters-1.0-SNAPSHOT.jar /opt/lab-6-characters/lab6-prof.jar

CMD ["java", "-jar", "/opt/lab-6-characters/lab6-prof.jar"]

# docker build -t d4m14n/aui-6-characters:v1.0 .\characters
# docker run --rm -p 8080:8080  -dit d4m14n/aui-6-characters:v1.0