### Get exisiting character

GET http://localhost:8080/api/characters/d6aa3095-e27d-4225-a2ef-8623400e91d5

### Get fake character

GET http://localhost:8080/api/characters/03668176-f8e7-4246-b0ed-e5d5b017d769

### Create new character

PUT http://localhost:8080/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Damian",
  "level": 12,
  "professionId": "8277e329-acd0-4aa5-8afc-56e93e5a2f2a"
}

### Patch character

PATCH http://localhost:8080/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
"name": "Damian",
"level": 13,
"professionId": "8277e329-acd0-4aa5-8afc-56e93e5a2f2a"
}

### Delete character

DELETE http://localhost:8080/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Get all characters

GET http://localhost:8080/api/characters







### Delete profession

DELETE http://localhost:8080/api/professions/0b07af3e-913e-4304-9473-f8be498f6a14

### Create new profession

PUT http://localhost:8080/api/professions/3a6f1eb1-8069-44ab-988f-d7fed2b65d81
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Student",
  "unlockLevel": 27
}



