FROM eclipse-temurin:17.0.6_10-jre

ENV SPRING_APPLICATION_NAME=lab4-professions
ENV RPG_CHARACTER_URL=http://localhost:8081

ENV CHARACTER_URL="http://spring-characters:8080"
ENV SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/professions_db"
ENV SPRING_DATASOURCE_DRIVERCLASSNAME="org.postgresql.Driver"
ENV SPRING_DATASOURCE_USERNAME="professions_user"
ENV SPRING_DATASOURCE_PASSWORD="professions_password"
ENV SPRING_JPA_DATABASE_PLATFORM="org.hibernate.dialect.PostgreSQLDialect"

ENV SERVER_PORT=8080
EXPOSE 8080

COPY lab4-professions/target/lab4-professions-1.0-SNAPSHOT.jar /opt/lab-6-professions/lab6-prof.jar

CMD ["java", "-jar", "/opt/lab-6-professions/lab6-prof.jar"]

# docker build -t d4m14n/aui-6-professions:v1.0 .\professions
# docker run --rm -p 8089:8080  -dit d4m14n/aui-6-professions:v1.0